doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
            datetime: \Carbon\Doctrine\DateTimeType
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/config/entity_binding/User'
                prefix: App\User\Domain\Entity
                type: xml
            ExpirationToken:
                is_bundle: false
                dir: '%kernel.project_dir%/src/FrameworkInfrastructure/Infrastructure/TemporaryToken'
                prefix: App\FrameworkInfrastructure\Infrastructure\TemporaryToken
                type: attribute

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    use_savepoints: true
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
