framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - App\FrameworkInfrastructure\Infrastructure\Middleware\ValidationMiddleware
            query.bus: ~

        failure_transport: failed

        transports:
            email:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: email
            command:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: command
            failed: '%env(MESSENGER_DEAD_LATER_QUEUE_DSN)%'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: email
            App\FrameworkInfrastructure\Domain\Command\CommandInterface: command

when@test:
    framework:
        messenger:
            transports:
                email:
                    dsn: 'in-memory://'
                    options:
                        queue_name: default
                command:
                    dsn: 'sync://'
                    options:
                        queue_name: command
