when@dev:
    nelmio_api_doc:
        areas:
            path_patterns:
                - ^/api(?!/doc$)

        documentation:
            info:
                title: My App
                description: This is an awesome app!
                version: 0.0.1

            paths:
                /api/login_check:
                    post:
                        tags:
                            - User
                        description: Login from email and password and get a JWT (could be called with GET method too)
                        summary: Login
                        requestBody:
                            required: true
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            email:
                                                type: string
                                            password:
                                                type: string