security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        jwt:
            lexik_jwt:
                class: App\User\Domain\Entity\User
#        app_user_provider:
#            entity:
#                class: App\User\Infrastructure\Security\SecurityUser
#                property: email
        security_user_provider:
            id: App\FrameworkInfrastructure\Infrastructure\Security\SecurityUserProvider
    firewalls:
        oAuth:
            pattern: ^/api/v1/oauth/check
            stateless: true
            provider: security_user_provider
            custom_authenticator:
                - App\FrameworkInfrastructure\Infrastructure\Security\OAuth\OauthAuthenticator

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                provider: security_user_provider

        api:
            pattern: ^/api
            stateless: true
            provider: jwt
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/login,            roles: PUBLIC_ACCESS            }
        - { path: ^/api/v1/oauth/check,   roles: PUBLIC_ACCESS            }
        - { path: ^/api/v1/user/login,    roles: PUBLIC_ACCESS            }
        - { path: ^/api/doc,              roles: PUBLIC_ACCESS            }
        - { path: ^/api,                  roles: IS_AUTHENTICATED_FULLY   }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
