version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '8080:80'
      - '4433:443'
    volumes:
      - .:/srv/www/cycleflow:ro
      - ./docker/nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - php
    networks:
      - main

  php:
    user: 1000:1000
    container_name: php
    working_dir: /srv/www/cycleflow
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/srv/www/cycleflow:rw
      - ./var:/srv/www/cycleflow/var:rw
    depends_on:
      - database
    networks:
      - main

  database:
    container_name: db
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - main

volumes:
  database_data:

networks:
  main:
    name: main