version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '3300:80'
    volumes:
      - ..:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html