App\User\Domain\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: email
        message: Un compte avec cette email existe déjà

  properties:
    email:
      - NotBlank:
          message: Veuillez remplir un email
      - Email:
          message: Votre email n'est pas valide
    username:
      - Length:
          max: 20
          min: 3
          minMessage: Votre nom d'utilisateur doit faire au moins 3 caractères
          maxMessage: Votre nom d'utilisateur ne doit pas faire plus de 20 caractères

    plainPassword:
      - NotCompromisedPassword:
          message: Votre mot de passe semble compromis, veuillez en changer
      - PasswordStrength:
          message: Votre mot de passe n'est pas assez solid
          minScore: 1